Repository IP-2025/waves-of-the-fallen, pull requests merged in 2025-04, with the labels that each got.

#70 Update issue templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/task-feature.md
Labels: documentation

#87 backend initial commit
  backend/.env.template
  backend/.gitignore
  backend/.prettierignore
  backend/.prettierrc
  backend/Dockerfile
  backend/README.md
  backend/docker-compose.yml
  backend/package-lock.json
  backend/package.json
  backend/rest-testing.http
  backend/src/app.ts
  backend/src/routes/auth.ts
  backend/src/routes/health.ts
  backend/src/server.ts
  backend/tsconfig.json
Labels: setup, backend

#81 79 Create movable character
  Game/Assets/Characters/place_holder/PlaceholderBody.png
  Game/Assets/Characters/place_holder/PlaceholderBody.png.import
  Game/Assets/Characters/place_holder/place_holder.tscn
  Game/Assets/Joystick/JoyBase.png
  Game/Assets/Joystick/JoyBase.png.import
  Game/Assets/Joystick/JoyHandle.png
  Game/Assets/Joystick/JoyHandle.png.import
  Game/Scenes/Characters/default_player.tscn
  Game/Scenes/Joystick/joystick.tscn
  Game/Scenes/Main.tscn
  Game/Scenes/Maps/default_map.tscn
  Game/Scripts/Characters/DefaultPlayer.cs
  Game/Scripts/Characters/DefaultPlayer.cs.uid
  Game/Scripts/Joystick/JoyHandle.cs
  Game/Scripts/Joystick/JoyHandle.cs.uid
  Game/Scripts/Joystick/Joystick.cs
  Game/Scripts/Joystick/Joystick.cs.uid
  Game/project.godot
Labels: setup

#123 Local multiplayer implemented
  Game/.editorconfig
  Game/Scenes/Characters/default_player.tscn
  Game/Scenes/Enemies/SpawnEnemies.tscn
  Game/Scenes/Joystick/joystick.tscn
  Game/Scenes/Main.cs
  Game/Scenes/Main.cs.uid
  Game/Scenes/Main.tscn
  Game/Scenes/Menu/localMenu.tscn
  Game/Scripts/Characters/BasicEnemy.cs
  Game/Scripts/Characters/DefaultPlayer.cs
  Game/Scripts/Enemies/SpawnEnemies.cs
  Game/Scripts/Enemies/SpawnEnemies.cs.uid
  Game/Scripts/Joystick/Joystick.cs
  Game/Scripts/Menu/LocalMenu.cs
  Game/Scripts/Multiplayer/GameManager.cs
  Game/Scripts/Multiplayer/GameManager.cs.uid
  Game/Scripts/Multiplayer/LocalMultiplayer.cs
  Game/Scripts/Multiplayer/LocalMultiplayer.cs.uid
  Game/Scripts/Multiplayer/PlayerInfo.cs
  Game/Scripts/Multiplayer/PlayerInfo.cs.uid
  Game/project.godot
Labels: enhancement

#178 #177 Add Solo mode (side quest and part of issue #175 multiplayer refactoring)
  Game/Scenes/GameRoot.tscn
  Game/Scenes/GameRoot/GameRoot.tscn
  Game/Scenes/Main.cs
  Game/Scenes/Menu/online_localMenu.tscn
  Game/Scenes/Multiplayer/Client.tscn
  Game/Scenes/Multiplayer/Server.tscn
  Game/Scenes/SpawnEnemies.cs.uid
  Game/Scripts/Characters/DefaultPlayer.cs
  Game/Scripts/GameRoot/GameRoot.cs
  Game/Scripts/GameRoot/GameRoot.cs.uid
  Game/Scripts/GameRoot/PlayerManager.cs
  Game/Scripts/GameRoot/PlayerManager.cs.uid
  Game/Scripts/Menu/LocalMenu.cs
  Game/Scripts/Menu/OnlineLocalMenu.cs
  Game/Scripts/Multiplayer/Command.cs
  Game/Scripts/Multiplayer/Command.cs.uid
  Game/Scripts/Multiplayer/EnemySpawner.cs
  Game/Scripts/Multiplayer/EnemySpawner.cs.uid
  Game/Scripts/Multiplayer/EntitySnapshot.cs
  Game/Scripts/Multiplayer/EntitySnapshot.cs.uid
  Game/Scripts/Multiplayer/EntityType.cs
  Game/Scripts/Multiplayer/EntityType.cs.uid
  Game/Scripts/Multiplayer/GameManager.cs
  Game/Scripts/Multiplayer/GameManager.cs.uid
  Game/Scripts/Multiplayer/LocalMultiplayer.cs
  Game/Scripts/Multiplayer/LocalMultiplayer.cs.uid
  Game/Scripts/Multiplayer/MultiplayerSyncronizer.cs.uid
  Game/Scripts/Multiplayer/NetworkManager.cs
  Game/Scripts/Multiplayer/NetworkManager.cs.uid
  Game/Scripts/Multiplayer/Serializer.cs
  Game/Scripts/Multiplayer/Serializer.cs.uid
  Game/Scripts/Multiplayer/Server.cs
  Game/Scripts/Multiplayer/Server.cs.uid
  Game/Scripts/Multiplayer/Snapshot.cs
  Game/Scripts/Multiplayer/Snapshot.cs.uid
  Game/Scripts/Waves/WaveTimer.cs
  Game/project.godot
Labels: feature, godot, maintenance
