Repository IP-2025/waves-of-the-fallen, pull requests merged in 2025-05, with the labels that each got.

#193 fix: Hide Online / Local menu
  Game/Scenes/Menu/online_localMenu.tscn
Labels: menu

#221 205 level up and unlock chars
  Game/Scenes/Menu/characterMenu.tscn
  Game/Scripts/Characters/CharacterManager.cs
  Game/Scripts/Menu/ButtonsCharacterSelection.cs
  Game/Scripts/Menu/Charactermenu.cs
Labels: godot, menu

#226 175 multiplayer complete refactoring to new hostclient logic
  Game/Scenes/Characters/default_player.tscn
  Game/Scenes/Characters/rider_enemy.tscn
  Game/Scenes/Enemies/SpawnEnemies.tscn
  Game/Scenes/GameRoot.tscn
  Game/Scenes/Menu/localMenu.tscn
  Game/Scenes/Menu/online_localMenu.tscn
  Game/Scenes/Multiplayer/Client.tscn
  Game/Scenes/Multiplayer/Server.tscn
  Game/Scenes/Waves/WaveTimer.tscn
  Game/Scripts/Characters/DefaultPlayer.cs
  Game/Scripts/Characters/EnemyBase.cs
  Game/Scripts/Characters/Health.cs
  Game/Scripts/Characters/MountedEnemy.cs
  Game/Scripts/Characters/mage.cs
  Game/Scripts/Enemies/SpawnEnemies.cs
  Game/Scripts/GameRoot/GameRoot.cs
  Game/Scripts/GameRoot/PlayerManager.cs
  Game/Scripts/GameRoot/PlayerManager.cs.uid
  Game/Scripts/Joystick/JoyHandle.cs
  Game/Scripts/Joystick/Joystick.cs
  Game/Scripts/Menu/LocalMenu.cs
  Game/Scripts/Menu/OnlineLocalMenu.cs
  Game/Scripts/Multiplayer/Client.cs
  Game/Scripts/Multiplayer/Client.cs.uid
  Game/Scripts/Multiplayer/Command.cs
  Game/Scripts/Multiplayer/EnemySpawner.cs
  Game/Scripts/Multiplayer/EnemySpawner.cs.uid
  Game/Scripts/Multiplayer/EntitySnapshot.cs
  Game/Scripts/Multiplayer/EntityType.cs
  Game/Scripts/Multiplayer/GameManager.cs
  Game/Scripts/Multiplayer/NetworkManager.cs
  Game/Scripts/Multiplayer/Serializer.cs
  Game/Scripts/Multiplayer/Server.cs
  Game/Scripts/Multiplayer/Server.cs.uid
  Game/Scripts/Multiplayer/Snapshot.cs
  Game/Scripts/Storage/SecureStorage.cs
  Game/Scripts/Waves/WaveTimer.cs
  Game/Scripts/Weapons/RangedWeapons.cs
  Game/project.godot
Labels: feature, maintenance

#241 Reimplemented headless server wait timer to prevent impatient users from clicking repeatedly
  Game/Scenes/Characters/default_enemy.tscn
  Game/Scenes/Characters/ranged_enemy.tscn
  Game/Scenes/Characters/rider_enemy.tscn
  Game/Scripts/Menu/LocalMenu.cs
  Game/Scripts/Menu/OnlineLocalMenu.cs
  Game/Scripts/Multiplayer/NetworkManager.cs
Labels: defect

#244 Bugfixes and maxEnemyLimit player scaling
  Game/Scenes/Characters/default_enemy.tscn
  Game/Scenes/Characters/mounted_enemy.tscn
  Game/Scenes/Characters/ranged_enemy.tscn
  Game/Scenes/Characters/rider_enemy.tscn
  Game/Scripts/Characters/Health.cs
  Game/Scripts/Characters/MountedEnemy.cs
  Game/Scripts/Enemies/SpawnEnemies.cs
  Game/project.godot
Labels: defect, maintenance

#255 FireStaff update bugfixes
  Game/Scenes/Characters/default_enemy.tscn
  Game/Scenes/Characters/mounted_enemy.tscn
  Game/Scenes/Characters/ranged_enemy.tscn
  Game/Scenes/Characters/rider_enemy.tscn
  Game/Scenes/Weapons/fireball.tscn
  Game/Scripts/Characters/Health.cs
  Game/Scripts/Weapons/FireBall.cs
Labels: defect, maintenance

#289 253 rider bugs sometimes
  Game/Entities/Enemies/Rider/MountedEnemy.cs
  Game/Entities/Enemies/Rider/Rider.cs
  Game/Entities/Enemies/Rider/mounted_enemy.tscn
  Game/Entities/Enemies/Rider/rider_enemy.tscn
  Game/Utilities/Gameflow/Spawn/Patterns/basic_enemy_x1_big.tscn
  Game/Utilities/Gameflow/Spawn/Patterns/mounted_enemy_x1.tscn
  Game/Utilities/Gameflow/Spawn/SpawnEnemies.cs
Labels: defect, maintenance

#303 165 weapon medicinebag
  Game/Entities/Characters/Base/DefaultPlayer.cs
  Game/Entities/Enemies/Rider/mounted_enemy.tscn
  Game/Utilities/Multiplayer/Client.cs
  Game/Utilities/Multiplayer/EntityType.cs
  Game/Utilities/Multiplayer/Server.cs
  Game/Weapons/Utility/MedicineBag/Medicine.cs
  Game/Weapons/Utility/MedicineBag/Medicine.cs.uid
  Game/Weapons/Utility/MedicineBag/MedicineBag.cs
  Game/Weapons/Utility/MedicineBag/MedicineBag.cs.uid
  Game/Weapons/Utility/MedicineBag/Resources/MedicineBag.png
  Game/Weapons/Utility/MedicineBag/Resources/MedicineBag1.png
  Game/Weapons/Utility/MedicineBag/Resources/MedicineBag2.png
  Game/Weapons/Utility/MedicineBag/medicine.tscn
  Game/Weapons/Utility/MedicineBag/medicineBag.tscn
Labels: feature, godot
